Yaoda E-Shop/Models/Clothes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Yaoda_E_Shop.Models
{
    public class Clothes
    {
        public int Id { get; set; }
    }
}

Yaoda E-Shop/Models/ErrorViewModel.cs
using System;

namespace Yaoda_E_Shop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Yaoda E-Shop/Models/Shoes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Yaoda_E_Shop.Models
{
    public class Shoes
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Preview")]
        public string ProductImageUrl { get; set; }
        [Display(Name="Product Name")]
        public string ProductName { get; set; }
        [Display (Name ="Description")]
        public string ProductDescription { get; set; }
        [Display (Name ="Price")]                   
        public double ProductPrice { get; set; }
        [Display(Name ="Quantity left")]
        public int ProductQuantity { get; set; }
    }
}

Yaoda E-Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Yaoda_E_Shop.Models;

namespace Yaoda_E_Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Yaoda E-Shop/Controllers/SneakersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Yaoda_E_Shop.Data;

namespace Yaoda_E_Shop.Controllers
{
    public class SneakersController : Controller
    {
        private readonly AppDbContext _context;
        public SneakersController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allSneakers = await _context.Sneakers.ToListAsync();
            return View(allSneakers);
        }
    }
}

Yaoda E-Shop/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="head">
    <img class="home-image" src="/images/12.png" />
    <h4 id="text">WELCOME TO YAODA'S E-SHOP. DON'T WAIT TO GET INTO OUR BRAND NEW COLLECTION!</h4>
</div>

<div class="button">
    <a class="home-button-link" asp-controller="Sneakers" asp-action="Index"><button class="button-design" type="button"><h3>Explore Our Products</h3></button></a>
    <a class="home-button-link" asp-controller="" asp-action=""><button class="button-design" type="button"><h3>Register Now</h3></button></a>
</div>

Yaoda E-Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Yaoda_E_Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/homeStyle.css" rel="stylesheet" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Yaoda E_Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="badge-info bi bi-house"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sneakers" asp-action="Index">PRODUCTS</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" style="padding-right:0.7rem">
                        <input name="searchString" type="text" class="form-control" placeholder="Search product..." />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Yaoda_E_Shop 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Yaoda E-Shop/Views/Sneakers/Index.cshtml
@*@model IEnumerable<Shoes> *@
@model List<Shoes>
@{ 
    ViewData["Title"] = "List of Products";
}
<div class="row">
    @foreach (var item in Model)
            {
                <div class="col-md-4 col-xs-6 border-primary mb-3">
                    <div class="card mb-3" style="max-width:540px">
                        <div class="row g-0">
                            <div class=" col-md-12">
                                <div class="card-header text-white bg-info">
                                    <p class="card-text">
                                        <h4 class="card-title">
                                            @item.ProductName 
                                            <a class="text-white float-right"><i class="bi bi-pencil-square"></i></a>
                                        </h4>
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <img src="@item.ProductImageUrl" width="100%" alt="">
                            </div>
                            <div class="col-md-6">
                                <div class="card-body">
                                    <p class="card-text"> <b >Price:  </b> @item.ProductPrice.ToString("c") </p>
                                    <p class="card-text"> <b>Quantity:</b>
                                    @if (item.ProductQuantity <= 10) { 
                                    <span> @item.ProductQuantity left, order soon!</span>}
                                    else { <span> @item.ProductQuantity</span>}
                                    </p>
                                </div>
                            </div>
                            <div class="col-md12">
                                <div class="card-footer">
                                    <p class="card-text">
                                        <a class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill"></i>See More</a>
                                        <a class="btn btn-success text-white float-left"><i class="bi bi-cart-plus"></i>Add to cart (@item.ProductPrice.ToString("c"))</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
</div>